### ISSUE TITLE
Double clicking empty display window causes NPE

### ISSUE THREAD

**Issue by pdbain** [pdbain/libris#33]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.lasalledebain.libris.ui.BrowserWindow.displaySelectedRecord(BrowserWindow.java:217)
	at org.lasalledebain.libris.ui.BrowserWindow$1.mouseClicked(BrowserWindow.java:231)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)

**Comment by pdbain** [comment]
Cannot reproduce.
